server:
  port: ${PORT:0} 

spring:
  #application:
    #name: sap-socios-service
 #config:
  #import: optional:configserver:http://localhost:8085
 #profiles:
    #active: pre 
  datasource:
   url: jdbc:mysql://localhost:3306/gorp-db-socios?useSSL=false&serverTimezone=America/Mexico_City 
   username: HGSAHOPRE
   password: HGSAhoPrePass
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
     ddl-auto: update
    generate-ddl: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
socio:
 mensaje: Hola, cambio dinamico con refreshScope.
